name: Remark Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install remark-cli remark-preset-lint-recommended remark-lint-list-item-indent

      - name: Run Remark
        run: npx remark . --use remark-preset-lint-recommended --use remark-lint-list-item-indent --frail
